AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline for OpenSupports

Parameters:
  SourceRepository:
    Type: String
    Description: The name of the CodeCommit repository
  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      PipelineName: !Sub "OpenSupports-${Environment}-Pipeline"
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref SourceRepository
                BranchName: main

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Sub "OpenSupports-${Environment}"
                TemplatePath: BuildOutput::infrastructure.yaml
                ParameterOverrides: !Sub |
                  {
                    "Environment": "${Environment}",
                    "DBPassword": "${DBPassword}",
                    "InstanceType": "${InstanceType}"
                  }
                RoleArn: !GetAtt DeploymentRole.Arn

  ArtifactBucket:
    Type: AWS::S3::Bucket

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Source:
        Type: CODECOMMIT
        Location: !Ref SourceRepository
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref CodePipeline
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildRole.Arn

Outputs:
  PipelineURL:
    Description: URL of the CodePipeline
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/codesuite/codepipeline/pipelines/${OpenSupports}-${Environment}/view"
